/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'inverse-primary': '#d0bcff',
        'on-primary-fixed': '#23005c',
        'secondary-fixed-dim': '#8bd6b4',
        'inverse-surface': '#2d3133',
        'on-secondary-fixed': '#002115',
        'surface-container-lowest': '#ffffff',
        secondary: '#1b6b4f',
        error: '#ba1a1a',
        'secondary-fixed': '#a6f2cf',
        'secondary-container': '#a6f2cf',
        'on-secondary': '#ffffff',
        'primary-fixed-dim': '#d0bcff',
        'error-container': '#ffdad6',
        background: '#f7f9fb',
        'on-primary': '#ffffff',
        'on-surface-variant': '#494454',
        'on-surface': '#191c1e',
        'on-primary-container': '#fffbff',
        'surface-container-high': '#e6e8ea',
        'outline-variant': '#cbc3d7',
        'primary-container': '#8455ef',
        tertiary: '#6d5e00',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'inverse-on-surface': '#eff1f3',
        'tertiary-fixed-dim': '#e2c62d',
        'on-secondary-container': '#247155',
        'on-secondary-fixed-variant': '#00513a',
        surface: '#f7f9fb',
        primary: '#6b38d4',
        'primary-fixed': '#e9ddff',
        'surface-bright': '#f7f9fb',
        'on-tertiary': '#ffffff',
        'on-tertiary-fixed-variant': '#524600',
        outline: '#7b7486',
        'surface-container-highest': '#e0e3e5',
        'surface-tint': '#6d3bd7',
        'on-primary-fixed-variant': '#5516be',
        'surface-container-low': '#f2f4f6',
        'surface-dim': '#d8dadc',
        'on-tertiary-container': '#4a3f00',
        'surface-variant': '#e0e3e5',
        'on-background': '#191c1e',
        'surface-container': '#eceef0',
        'tertiary-container': '#c4ab01',
        'on-tertiary-fixed': '#211b00',
        'tertiary-fixed': '#ffe24c',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        gutter: '24px',
        'organic-offset': '12px',
        'container-max': '1280px',
        unit: '8px',
        'margin-mobile': '16px',
        'margin-desktop': '40px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      fontFamily: {
        'label-sm': ['Hanken Grotesk'],
        'headline-sm': ['Bricolage Grotesque'],
        'display-lg': ['Bricolage Grotesque'],
        'label-bold': ['Hanken Grotesk'],
        'body-lg': ['Hanken Grotesk'],
        'display-lg-mobile': ['Bricolage Grotesque'],
        'headline-md': ['Bricolage Grotesque'],
        'body-md': ['Hanken Grotesk'],
      },
      fontSize: {
        'label-sm': ['12px', { lineHeight: '1.0', fontWeight: '500' }],
        'headline-sm': ['24px', { lineHeight: '1.2', fontWeight: '700' }],
        'display-lg': ['56px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
        'label-bold': ['14px', { lineHeight: '1.0', letterSpacing: '0.05em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'display-lg-mobile': ['40px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-md': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
